name: Run temps.py and commit JSON files

on:
  schedule:
    - cron: '59 23 * * *'  # Executa cada dia a les 23:59 UTC
  workflow_dispatch:

jobs:
  run-temps:
    runs-on: ubuntu-latest

    steps:
    # Clona el repositori
    - name: Checkout repository
      uses: actions/checkout@v4

    # Configura Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Instal·la dependències (si n'hi ha)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Executa el programa temps.py
    - name: Run temps.py
      run: python temps.py

    # Configura Git
    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    # Afegeix i commiteja els fitxers .json generats
    - name: Commit JSON files
      run: |
        git add *.json
        git commit -m "Add generated JSON files from temps.py" || echo "No JSON files to commit"

    # Puja els canvis al repositori
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # Canvia a la branca que utilitzis (ex. 'main' o 'master')
